config/routes.rb
require 'subdomain'
Rails.application.routes.draw do
   
  resources :attachments
  
  get 'search/post'
  post 'search/fetch_post'
  get 'search/user'

  namespace :administrator do
    resources :roles
  end
  resources :activities
  resources :colleges do
    post :import, on: :collection
  end
  resources :answers
  resources :questions
  resources :content_images
  resources :post_category_images
  resources :profiles, param: :user_name do
    member do
      get :education
      get :basic_info
      get :social_info
      get :school_info
      get :college_info
      get :experience
      get :achievement
      get :project
      get :activity
      get :contributions
      resources :achievements
      resources :projects
      resources :experiences, param: :id
      resources :school_details
      resources :college_details
    end
  end
  
  root 'home#index'
  get 'home' => 'home#index', as: 'home'
  get 'browse_posts' => 'home#browse_posts', as: 'browse_posts'
  get 'help' => 'home#help', as: 'help'
  get 'join_us' => 'home#join_us', as: 'join_us'
  get 'to_do' => 'home#to_do', as: 'to_do'
  get 'volunteering' => 'home#volunteering', as: 'volunteering'
  get 'tags/:tag', to: 'home#tags', as: :tag
  
  resources :subscriptions
  
  namespace :administrator do
    resources :channel_types
    resources :channels
    resources :statuses
    resources :post_categories do
      get :fetch_categories_for_type, on: :collection
    end
    resources :posts do
      get '(page/:page)', :action => :index, :on => :collection, :as => ''
    end
  end
  resources :channels, except: :destory do
    collection do
      get :list_channels
      get :explore
      get :browse
      get :recommended
      get :my
    end
    member do 
      post :subscribe
      post :unfollow
      resources :channel_images
      get :followers
    end
    get :new_index
    resources :assignments
    resources :posts, only: :index, on: :member
  end
  resources :posts, param: :slug do
    get :my, on: :collection
    get :latest_post, on: :collection
    member do
      post :like
      post :dislike
      resources :embed_codes
      resources :post_images
      resources :post_contents
      resources :comments do 
        post :report_abuse
        get :reply
      end
    end
     get '(page/:page)', :action => :index, :on => :collection, :as => ''
  end

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks',
                                    registrations: 'users/registrations' }
  
  resources :users, param: :user_name do 
    collection do 
      get :pending
      get :completed
      get :incomplete
      get :sign_in_popup
    end
    member do
      get :following
      get :followers
      get :subscription
      get :my_classes
      get :manage_subscriptions
      get :fetch_receiver
      post :subscribe
      post :unfollow
      resources :messages do
        get '(page/:page)', :action => :index, :on => :collection, :as => ''
      end
    end
  end
  
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  helper_method :resource_name, :resource, :devise_mapping
  def index
  	@posts = Post.includes(:channel, :votes, 
                           :user, :post_images
                          ).active.order('id desc').page(params[:page]).per(20)
    # if params[:tag]
   #    @posts = Post.includes(:channel, :votes, 
   #                           :user, :post_images
   #                          ).tagged_with(params[:tag]).page(params[:page]).per(5)
   #  else  
   #    @posts = if @channel
   #               @channel.posts.includes(:channel, :votes, 
   #                                       :user, :post_images).active.page(params[:page]).per(5)
   #             else
   #                Post.includes(:channel, :votes, 
   #                              :user, :post_images).active.page(params[:page]).per(5)
   #             end
   #  end
    @channels = {}
    @channels[:latest]  = Channel.last(20)
    @channels[:popular] = Channel.joins(:subscriptions
                                       ).select('channels.*,
                                                 count(subscriptions.*) 
                                                 as subscribed_count'
                                                ).group('channels.id'
                                                       ).order('subscribed_count DESC'
                                                              ).limit(20)
    @contributors = User.joins(:posts
                              ).select('users.*, count(posts.*) as post_count'
                                      ).group('users.id').order('post_count DESC')
    @weekly_hits = {}
    @weekly_hits[:posts] = Post.joins(:votes
                              ).select('posts.*, 
                                        count(votes.*) as votes_count'
                                      ).where('votes.vote_flag =? 
                                              AND posts.updated_at BETWEEN ? AND ?',
                                              true, Time.now - 1.year, Time.now
                                             ).order('votes_count DESC'
                                                    ).group('posts.id')
    @weekly_hits[:channels] = (Channel.joins(:subscriptions)
                                      .select('channels.*, count(subscriptions.*) as subscribed_count')
                                      .where('subscriptions.subscribe = ? AND channels.updated_at BETWEEN ? AND ?',
                                             true, Time.now - 1.week,
                                             Time.now).group('channels.id').order('subscribed_count DESC'))
    # @posts = Post.includes(:votes, :post_images).joins(channel: :channel_type).select("posts.*, channels.id, channels.name as channel_name, channel_types.id, channel_types.title as channel_type").group('channel_type')
  end

  def help

  end
  
  def to_do

  end

  def browse_posts
    @posts = Post.where("lower(name) ilike ?",
                         [params[:char].squish, '%'].join
                       ).page(params[:page])
  end

  def browser_channel

  end

  def browse_tags
    @tags = {} 
    @tags[:list] = Tag.list
    @tags[:popular_post] = Tag.popular_post(params[:name], params[:char])
  end
  
  def tags
    @posts = Post.includes(:channel, :votes, 
                             :user, :post_images
                            ).tagged_with(params[:tag]
                                         ).order('updated_at DESC').page(params[:page])
  end
  
  def join_us
  end

  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_ex_channels.html.haml
= stylesheet_link_tag('slick-theme.css', 'slick.css')
= javascript_include_tag('slick.min.js', 'explore_channels.js')
.row.white-backgrnd
  - if channels.present?
    - channels.each do |channel|
      .large-12.columns
        .channel-container{:style => "padding: 10px"}
          .row.collapse
            .large-8.columns{:style => "padding-top: 10px"}
              %h6
                = link_to channel.name, channel_posts_path(channel)
              = channel.description[0..75]
            .large-4.columns
              .row.collapse.user-stats
                .small-4.columns
                  %h5.text-center= channel.posts.size
                  %span Posts
                .small-4.columns
                  %h5.text-center= channel.subscriptions.size
                  %span Followers
                .small-4.columns
                  %br
                    %span= render 'channels/subscription', channel: channel, label: 'Following'
      %hr
  - else
    .large-12.columns.text-center
      No results for this particular category

app/views/home/_home_ex_channel.html.haml
- channels.each do |channel|
  %li{style: 'width: 217px;'}
    = render 'channels/list_ch', channel: channel

app/views/home/_join_us.html.haml
.full-width.row
	.large-4.medium-4.columns.join-us-cover{style: "min-height: 25em"}
		.student-cover-img
		.text-center{style: 'padding-top: 22em'} 
			.button.radius.tiny.secondary
				Hello Student Register
	.large-4.medium-4.columns.join-us-cover{style: "min-height: 25em"}
		.mentor-cover-img
		.text-center{style: 'padding-top: 22em'} 
			.button.radius.tiny.secondary
				Hello Mentor Register 
	.large-4.medium-4.columns.join-us-cover{style: "min-height: 25em"}
		.school-cover-img
		.text-center{style: 'padding-top: 22em'} 
			.button.radius.tiny.secondary
				Institution Register 

app/views/home/_latest_post.html.haml
- posts.each do |post|
  - likes = post.votes.select(&:vote_flag).size
  - dislikes = post.votes.reject(&:vote_flag).size
  .white-backgrnd.post-list
    .post-container
      %header#post_id{value: post.id, style: 'border-bottom: 1px solid #ddd; padding-top: 0.5em;'}
        = link_to post.name, post_path(post)
        %small
          from
          = post.channel.name
          = time_ago_in_words(post.updated_at)
          ago
        -# if current_user
          %a{"data-dropdown" => "hover-#{post.id}", "data-options" => "is_hover:true; hover_timeout:100", :href => "javascript:void(0)", style: 'float:right'}
            %i.fa.fa-navicon
          %ul.f-dropdown{"data-dropdown-content" => "", :id => "hover-#{post.id}"}
            %li
              = render 'channels/subscription', channel: post.channel
      %ul.inline
        - post.tags.each do |tag|
          %li.label.secondary
            = raw link_to tag.name, tag_path(tag.name)  
      .thumbnail.show-for-small
        = image_tag(post.try(:post_images).try(:first).try(:image) || 'oogway-wifi.png', height: '150', width: '180', class: 'th')
      .row.collapse
        .large-8.columns
          %p.hide-for-small= raw post.description[0..150]
          %br
          %i.fa.fa-thumbs-up{title: 'likes'}= likes
          &nbsp;
          %i.fa.fa-thumbs-down{title: 'dislikes'}= dislikes
          &nbsp;
          %i.fa.fa-comments{title: 'comments'}= post.comments.size
        .large-4.small-12.columns
          .thumbnail.hide-for-small{style: 'padding: 1em'}
            = image_tag(post.try(:post_images).try(:first).try(:image).try(:small) || 'oogway-wifi.png',align: 'right', class: 'th')
          

- if @posts.present?
  %div
    = paginate @posts

app/views/home/_popular_channels.html.haml
/ %link{:href => "//cdn.jsdelivr.net/jquery.slick/1.5.9/slick.css", :rel => "stylesheet", :type => "text/css"}/
/ %link{:href => "//cdn.jsdelivr.net/jquery.slick/1.5.9/slick-theme.css", :rel => "stylesheet", :type => "text/css"}/
/ %script{:src => "//cdn.jsdelivr.net/jquery.slick/1.5.9/slick.min.js", :type => "text/javascript"}

-#%div{:style => "margin: 1em"}
  %header.text-center{:style => "border: 1px solid #5cb767;"}
    Popular Channels
  .slider-nav{:style => "border: 1px solid #5cb767"}
    - channels.each do |channel|
      %div  
        %header{:style => "padding: 5px;border-bottom: 1px solid #ddd"}
          = link_to channel.name, channel_path(channel)
          %br
        = raw channel.description[0..75]
        = link_to 'Read more..', channel_path(channel)

%ul.no-bullet
  %li.text-center{:style => "border: 1px solid #ddd;"}
    \ Popular Channels
  - channels.each do |channel|
    %li.relatedWrapper
      .row.collapse
        .large-7.columns{:style => "padding-left: 0.3em;"}
          = link_to channel.name, channel_path(channel)
          %br
          = raw channel.description[0..250]
        .large-5.columns{:style => "padding-left: 0.3em; margin-top: 0.5em;  margin-bottom: 0.5em"}
          = link_to image_tag(channel.channel_images.first.try(:image).try(:small) || 'oogway-wifi.png', height: '75', width: '75', class: 'th', align: 'left'), channel_path(channel)



:javascript
  $(document).ready(function(){
    $('.slider-nav').slick({
      dots: false,
      autoplay: true,
      infinite: true,
      speed: 1000,
      cssEase: 'linear',
      responsive: [
                    {
                      breakpoint: 1024,
                      settings: {
                        slidesToShow: 3,
                        slidesToScroll: 3,
                        infinite: true,
                        dots: false
                      }
                    },
                    {
                      breakpoint: 600,
                      settings: {
                        slidesToShow: 2,
                        slidesToScroll: 2
                      }
                    },
                    {
                      breakpoint: 500,
                      settings: {
                        slidesToShow: 1,
                        slidesToScroll: 1
                      }
                    }
                      // You can unslick at a given breakpoint now by adding:
                      // settings: "unslick"
                      // instead of a settings object
                  ]
    });
  })

app/views/home/_post.html.haml
- @posts.each do |post|
  - likes = post.votes.select(&:vote_flag).size
  - dislikes = post.votes.reject(&:vote_flag).size
  %li
    %article.article-card
      %img{src: (post.post_images.try(:first).try(:image).try(:medium) || 'assets/no-image.jpg'), width: 250}
      .card-content
        %post-author
          %small 
            By
            %a{href: 'javascript:void(0)'}= post.user.email
          %h6
            %a{href: post_path(post)}= post.name
        .content
          = raw post.description[0..100]
        .row
          %small
            %a
              %i.fa.fi-heart.fa-thumbs-up{title: 'likes'}= likes
            %a
              %i.fa.fi-heart.fa-thumbs-down{title: 'dislikes'}= dislikes
            %a
              %i.fa.fi-heart.fa-comments{title: 'comments'}= post.comments.size
        %a{href: post_path(post)} Read on...
%div
  = paginate @posts

app/views/home/browse_posts.html.haml
.row{style: 'padding-top:1em'}
	.large-8.columns
		= render 'posts/post'
	.large-4.columns.white-backgrnd
		.pad-1
			= render 'devise/shared/login'
		%div
			= render 'shared/tags', tags: Tag.popular_post, header: 'Popular Tags'

app/views/home/browse_tags.html.haml
.full-width
	.row.pad-1
		- @tags[:list].each do |tag|
			= tag.name

app/views/home/help.html.haml
%br
.row
	%ul.large-block-grid-3
		%li
			%header{style: 'border-bottom: 1px solid #ddd'}
				\ Account	
			%h4
				%small
					What topics can I ask about here?
					%br
					What topics can I ask about here? 
		%li
			%header{style: 'border-bottom: 1px solid #ddd'}
				\ Our model
			%h4
				%small
					What topics can I ask about here?
					%br
					What topics can I ask about here? 
		%li
			%header{style: 'border-bottom: 1px solid #ddd'}
				\ Reputation
			%h4
				%small
					What topics can I ask about here?
					%br
					What topics can I ask about here? 
	%ul.large-block-grid-3
		%li
			%header{style: 'border-bottom: 1px solid #ddd'}
				\ Channels
			%h4
				%small
					What topics can I ask about here?
					%br
					What topics can I ask about here? 
		%li
			%header{style: 'border-bottom: 1px solid #ddd'}
				\ Posts
			%h4
				%small
					What topics can I ask about here?
					%br
					What topics can I ask about here? 
		%li
			%header{style: 'border-bottom: 1px solid #ddd'}
				\ Badges
			%h4
				%small
					What topics can I ask about here?
					%br
					What topics can I ask about here?  

app/views/home/index.html.haml
%section.welcome
  .intro
    %h2.text-center
      %p= image_tag('ooggsb.png', height: '100', width: '100')
      %strong
        Welcome to Oogway
  %div.text-center
    %h4{style: 'color: #fff; padding-left: 1em;'}
      Connect with teachers, mentors, recruiters & fellow students
      %br
      Learn, Share & Care
  - unless current_user
    %hr{style: "width: 45%; margin-left: 28%;border-color: black;"}
    %div.text-center  
      = link_to "Sign up", new_user_registration_path,class: 'button tiny radius', style: 'background-color: #7030A0;'
      = link_to "Login", new_user_session_path, class: 'button tiny radius  success'

-#%section
  .row.collapse{style: 'min-height: 17em; padding-top: 1em'}
    .large-4.medium-4.columns
      = image_tag('share-good.png')
    .large-8.medium-8.columns
      %h5
        %strong{style: 'color: blue'}
          Tiny drops maketh a ocean. Oogway will serve as a medium for people who are experts in their fields to share their views and experience. What you share in Oogway will play a great role in shaping one’s life.
  .row.collapse{style: 'min-height: 15em'}
    .large-4.medium-4.columns
      = image_tag('group-share.png')
    .large-8.medium-8.columns
      %h5
        %strong{style: 'color: blue'}
          You will also get an opportunity to interact with like mentors, industry experts, teachers and students. 
      %strong
        = link_to "Join us to create a better world.", new_user_registration_path, style: 'color: purple'
.how-it-works#how-it-works
  %h2.text-center
    %strong{style: "color: #008cba;"}
      How it works
  .row 
    .contents  
      .large-4.medium-4.columns{style: 'border-right: 2px solid lightblue'}
        = image_tag('channel-new.png')
        .text-center Create or Follow a channel
      .large-4.medium-4.columns{style: 'border-right: 2px solid lightblue'}
        = image_tag('post_thought.png')
        .text-center Post your thoughts
      .large-4.medium-4.columns
        = image_tag('interact-new.png')
        .text-center  Discuss with experts
      -#.large-3.medium-3.columns
        = image_tag('idea-new.png')
        .text-center  And Improve 
  .row{style: 'padding-top: 1em;'}
    %div{style: 'font-style: italic;'} 
      Tiny drops maketh a ocean. Oogway will serve as a medium for people who are experts in their fields to share their views and experience. What you share in Oogway will play a great role in shaping one’s life.
.clearfix
-#  
  = render 'join_us'
  .row
    .text-center
      %h4{:style => " color: purple"}
        = image_tag('turtle-icon.png', height: '50', width: '50')
        %strong
          Join OogWay. Its free.
      = link_to "Sign up", new_user_registration_path,class: 'button tiny radius', style: 'background-color: #7030A0; border: 1px solid #fff'
      = link_to "Login", new_user_session_path, class: 'button tiny radius success'

app/views/home/join_us.html.haml
.full-width.row
	.large-4.medium-4.columns.join-us-cover{style: "min-height: 25em"}
		.student-cover-img
		.text-center{style: 'padding-top: 22em'} 
			.button.radius.tiny.secondary
				Hello Student Register
	.large-4.medium-4.columns.join-us-cover{style: "min-height: 25em"}
		.mentor-cover-img
		.text-center{style: 'padding-top: 22em'} 
			.button.radius.tiny.secondary
				Hello Mentor Register 
	.large-4.medium-4.columns.join-us-cover{style: "min-height: 25em"}
		.school-cover-img
		.text-center{style: 'padding-top: 22em'} 
			.button.radius.tiny.secondary
				Institution Register 

app/views/home/parallax.html.haml
= javascript_include_tag "scroll_deck/jquery.easing.1.3.js", "scroll_deck/jquery.scrollrama.js", "scroll_deck/jquery.scrolldeck.js", "scroll_deck/jquery.scrollTo-1.4.3.1.min.js", "scroll_deck/jquery.parallax-1.1.js"
= stylesheet_link_tag "scroll_deck/style.css" 

:javascript
  $(document).ready(function(){
    //$('#nav').localScroll(800);
    
    RepositionNav();
    
    $(window).resize(function(){
      RepositionNav();
    }); 
    
    //.parallax(xPosition, adjuster, inertia, outerHeight) options:
    //xPosition - Horizontal position of the element
    //adjuster - y position to start from
    //inertia - speed to move relative to vertical scroll. Example: 0.1 is one tenth the speed of scrolling, 2 is twice the speed of scrolling
    //outerHeight (true/false) - Whether or not jQuery should use it's outerHeight option to determine when a section is in the viewport
    $('#intro').parallax("54%", 500, 0.1, true);
    $('#second').parallax("50%", 0, 0.1, true);
    $('.bg').parallax("50%", 2500, 0.4, true);
    $('#third').parallax("50%", 2700, 0.1, true);
    
    var deck = new $.scrolldeck({
      slides: '.slide',
      buttons: '#nav li a',
      easing: 'easeInOutExpo'
    });

  })
  
%ul#nav
  %li
    %a{:href => "#intro", :title => "Next Section"}
  %li
    %a{:href => "#second", :title => "Next Section"}
  %li
    %a{:href => "#third", :title => "Next Section"}
  %li
    %a{:href => "#fifth", :title => "Next Section"}
#intro.slide
  .story
    .float-left
      %h2 Oogway
      %p This section has a background that moves slightly slower than the user scrolls. This is achieved by changing the top position of the background for every pixel the page is scrolled.
  / .story
/ #intro
#second.slide
  .story
    / <div class="bg"></div>
    .float-right
      %h2 Multiple Backgrounds
      %p The multiple backgrounds applied to this section are moved in a similar way to the first section -- every time the user scrolls down the page by a pixel, the positions of the backgrounds are changed.
      %p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean nibh erat, sagittis sit amet congue at, aliquam eu libero. Integer molestie, turpis vel ultrices facilisis, nisi mauris sollicitudin mauris, volutpat elementum enim urna eget odio. Donec egestas aliquet facilisis. Nunc eu nunc eget neque ornare fringilla. Nam vel sodales lectus. Nulla in pellentesque eros. Donec ultricies, enim vitae varius cursus, risus mauris iaculis neque, euismod sollicitudin metus erat vitae sapien. Sed pulvinar.
  / .story
/ #second
#third.slide
  .story
    .float-left
      %h2 What Happens When JavaScript is Disabled?
      %p The user gets a slap! Actually, all that jQuery does is moves the backgrounds relative to the position of the scrollbar. Without it, the backgrounds simply stay put and the user would never know they are missing out on the awesome! CSS2 does a good enough job to still make the effect look cool.
  / .story
/ #third
#fifth.slide
  .story
    .text-center
      Blah
    / .story
/ #fifth
.full-width
  %br
  -#
    .row{style: 'border: 1px solid #ddd; height: 15em; padding: 1em'}
      %ul.tabs{"data-tab" => ""}
        %li.tab-title.active{style: 'border: 1px solid #ddd; width: 25%'}
          %a{ href: '#oogway'} 
            %h4
              %small Oogway
        %li.tab-title{style: 'border: 1px solid #ddd;  width: 25%'}
          %a{ href: '#creating_channel' } 
            %h4
              %small What's a Channel?
        %li.tab-title{style: 'border: 1px solid #ddd;  width: 25%'}
          %a{ href: '#creating_post' } 
            %h4
              %small What is a post?
        %li.tab-title{style: 'border: 1px solid #ddd;  width: 25%'}
          %a{ href: '#build_better_world' } 
            %h4
              %small Let build a better world
      .tabs-content
        #oogway.content.active
          Oogway the community to share knowledge, experience gained in performing certain things and help other from falling into pits and loop holes. Share to make the world a better place.
          What we believe in is, every one is a master mind in their own way. Rather than building things individually, come lets build a world together for a better tomorrow.
        #creating_channel.content
          What is a channel.
        #creating_post.content
          Changing the social network to achieve full its full power
        #build_better_world.content
          Lets build better world by learn and let learn motive
      
  
    %br    
    .row
      .large-4.columns
        %header
          Post of the week
        %ul.no-bullet
          - @weekly_hits[:posts].each do |post|
            %li.relatedWrapper
              .row
                .large-4.columns
                  = link_to image_tag(post.post_images.first.try(:image).try(:small), class: 'th', align: 'left'), post_path(post)
                .large-8.columns
                  = link_to post.name, post_path(post)
                  = raw post.description[0..75]
                  = post.votes_count
      .large-4.columns
        %header
          Channel of the week
        %ul.no-bullet
          - @weekly_hits[:posts].each do |post|
            %li.relatedWrapper
              .row
                .large-4.columns
                  = link_to image_tag(post.post_images.first.try(:image).try(:small), class: 'th', align: 'left'), post_path(post)
                .large-8.columns
                  = link_to post.name, post_path(post)
                  = raw post.description[0..75]
                  = post.votes_count
      .large-4.columns
        %header
          Contributor of the week
        %ul.no-bullet
          - @weekly_hits[:posts].each do |post|
            %li.relatedWrapper
              .row
                .large-4.columns
                  = link_to image_tag(post.post_images.first.try(:image).try(:small), class: 'th', align: 'left'), post_path(post)
                .large-8.columns
                  = link_to post.name, post_path(post)
                  = raw post.description[0..75]
                  = post.votes_count
    .row
      .large-8.columns
        %header.white-backgrnd{style: 'border: 1px solid #ddd;padding: 1em;'}
          Latest Topics
        .home-posts{style: 'border: 1px solid #ddd;height: 60em; padding: 1em;overflow: auto;'}
          = render 'latest_post', posts: @posts.first(5)
      .large-4.columns
        .post_week{style: 'border: 1px solid #ddd; padding: 1em'}
          %header Post of the week
          %hr
          Post which got most likes, comments and less dislike
        %br
        .channel_week{style: 'border: 1px solid #ddd; padding: 1em'}
          %header Channel of the week
          %hr
          Channel which got most Post, Follower and less unfollowers
        %br
        .news{style: 'border: 1px solid #ddd; padding: 1em'}
          %header News
          %hr
          All news happenning in oogway new features which are about to add and other stuff like a school joined oogway
          Atleast 5 news to shown, awards what ever related
        %br
        .events{style: 'border: 1px solid #ddd; padding: 1em'}
          %header Events
          %hr
          All events happenning in oogway like seminar conducted in other schools and colleges
          Atleast 5 news to shown, awards what ever related
    %br
    .row
      .large-8.columns
        %header.white-backgrnd{style: 'border: 1px solid #ddd;padding: 1em;'}
          Popular Channels
        .home-channels{style: 'border: 1px solid #ddd; padding: 1em;'} 
          %ul.large-block-grid-3.small-block-grid-1.medium-block-grid-2
            = render 'home_ex_channel', channels: @channels[:popular].first(5)
      .large-4.columns
        .testimonials
          %header
            Testimonies
          %blockquote
            Oogway a great thing we need now. Its a social network but used for a better purpose.
        .testimonials
          %header
            Testimonies
          %blockquote
            Oogway a great thing we need now. Its a social network but used for a better purpose.
        .testimonials
          %header
            Testimonies
          %blockquote
            Oogway a great thing we need now. Its a social network but used for a better purpose.
        .oogway-video{style: 'border: 1px solid #ddd; padding: 1em'}
          %header
            Oogway Videos
          .content
            Videos about oogway


    %br
    .row.text-center
      %header
        Top Contributors
      %ul.large-block-grid-3.small-block-grid-1.medium-block-grid-2
        - @contributors.each do |us|
          %li
            = link_to image_tag(us.profile.try(:avatar).try(:small) || 'bvs.jpg', class: 'th' ), profile_path(user_name: (us.user_name || us))

    %br
    .row
      %header.text-center
        Top Contributors
      .team-pics
        %br
        %ul.large-block-grid-3.small-block-grid-1.medium-block-grid-2
          - 5.times do |i|
            %li
              = link_to image_tag('bvs.jpg', class: 'th'), 'javascript:void(0)'
              Author Name
          %li
            How to become a top contributor

app/views/home/to_do.html.haml
%br
.row
	TO DO
	%hr
	%ul.large-block-grid-4
		%li
			Activity , get suggestions from user in some survey channel which every user had to follow
		%li
			Create Cv
		%li
			JOBS, search companies but irrelevant
		%li
			forgot attachments other than images, forgot internship

app/views/home/volunteering.html.haml
%br
.row
	Volunteering Platform