config/routes.rb
require 'subdomain'
Rails.application.routes.draw do
   
  resources :attachments
  
  get 'search/post'
  post 'search/fetch_post'
  get 'search/user'

  namespace :administrator do
    resources :roles
  end
  resources :activities
  resources :colleges do
    post :import, on: :collection
  end
  resources :answers
  resources :questions
  resources :content_images
  resources :post_category_images
  resources :profiles, param: :user_name do
    member do
      get :education
      get :basic_info
      get :social_info
      get :school_info
      get :college_info
      get :experience
      get :achievement
      get :project
      get :activity
      get :contributions
      resources :achievements
      resources :projects
      resources :experiences, param: :id
      resources :school_details
      resources :college_details
    end
  end
  
  root 'home#index'
  get 'home' => 'home#index', as: 'home'
  get 'browse_posts' => 'home#browse_posts', as: 'browse_posts'
  get 'help' => 'home#help', as: 'help'
  get 'join_us' => 'home#join_us', as: 'join_us'
  get 'to_do' => 'home#to_do', as: 'to_do'
  get 'volunteering' => 'home#volunteering', as: 'volunteering'
  get 'tags/:tag', to: 'home#tags', as: :tag
  
  resources :subscriptions
  
  namespace :administrator do
    resources :channel_types
    resources :channels
    resources :statuses
    resources :post_categories do
      get :fetch_categories_for_type, on: :collection
    end
    resources :posts do
      get '(page/:page)', :action => :index, :on => :collection, :as => ''
    end
  end
  resources :channels, except: :destory do
    collection do
      get :list_channels
      get :explore
      get :browse
      get :recommended
      get :my
    end
    member do 
      post :subscribe
      post :unfollow
      resources :channel_images
      get :followers
    end
    get :new_index
    resources :assignments
    resources :posts, only: :index, on: :member
  end
  resources :posts, param: :slug do
    get :my, on: :collection
    get :latest_post, on: :collection
    member do
      post :like
      post :dislike
      resources :embed_codes
      resources :post_images
      resources :post_contents
      resources :comments do 
        post :report_abuse
        get :reply
      end
    end
     get '(page/:page)', :action => :index, :on => :collection, :as => ''
  end

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks',
                                    registrations: 'users/registrations' }
  
  resources :users, param: :user_name do 
    collection do 
      get :pending
      get :completed
      get :incomplete
      get :sign_in_popup
    end
    member do
      get :following
      get :followers
      get :subscription
      get :my_classes
      get :manage_subscriptions
      get :fetch_receiver
      post :subscribe
      post :unfollow
      resources :messages do
        get '(page/:page)', :action => :index, :on => :collection, :as => ''
      end
    end
  end
  
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

end

app/models/college.rb
require 'roo'
class College < ActiveRecord::Base
	def self.import(file)
	  spreadsheet = open_spreadsheet(file)
	  header = spreadsheet.row(1)
	  (2..spreadsheet.last_row).each do |i|
	    row = Hash[[header, spreadsheet.row(i)].transpose]
	    college = find_by_code(row["code"]) || new
	    college.code = row["code"]
	    college.name = row["name"]
	    college.location = row["location"]
	    college.save!
	  end
	end

	def self.open_spreadsheet(file)
	  case File.extname(file.original_filename)
	  when ".csv" then Csv.new(file.path, nil, :ignore)
	  when ".xls" then Excel.new(file.path, nil, :ignore)
	  when ".xlsx" then Roo::Excelx.new(file.path, extension: :xlsx)
	  else raise "Unknown file type: #{file.original_filename}"
	  end
	end


end

app/controllers/colleges_controller.rb
class CollegesController < ApplicationController
  before_action :set_college, only: [:show, :edit, :update, :destroy]

  # GET /colleges
  # GET /colleges.json
  def index
    @colleges = College.all
  end

  # GET /colleges/1
  # GET /colleges/1.json
  def show
  end

  # GET /colleges/new
  def new
    @college = College.new
  end

  # GET /colleges/1/edit
  def edit
  end

  # POST /colleges
  # POST /colleges.json
  def create
    @college = College.new(college_params)

    respond_to do |format|
      if @college.save
        format.html { redirect_to @college, notice: 'College was successfully created.' }
        format.json { render :show, status: :created, location: @college }
      else
        format.html { render :new }
        format.json { render json: @college.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /colleges/1
  # PATCH/PUT /colleges/1.json
  def update
    respond_to do |format|
      if @college.update(college_params)
        format.html { redirect_to @college, notice: 'College was successfully updated.' }
        format.json { render :show, status: :ok, location: @college }
      else
        format.html { render :edit }
        format.json { render json: @college.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colleges/1
  # DELETE /colleges/1.json
  def destroy
    @college.destroy
    respond_to do |format|
      format.html { redirect_to colleges_url, notice: 'College was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    College.import(params[:file])
    redirect_to root_url, notice: "Products imported."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_college
      @college = College.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def college_params
      params.require(:college).permit(:code, :name, :location)
    end
end

app/helpers/colleges_helper.rb
module CollegesHelper
end

app/views/colleges/_form.html.erb
<%= semantic_form_for @college do |f| %>
  <%= f.inputs do %>
    <%= f.input :code %>
    <%= f.input :name %>
    <%= f.input :location %>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :input %>
  <% end %>
<% end %>


<div class="row">
	Import Products
	<%= form_tag import_colleges_path, multipart: true do %>
	  <%= file_field_tag :file %>
	  <%= submit_tag "Import" %>
	<% end %>
</div>

app/views/colleges/edit.html.erb
<h1>Editing College</h1>

<%= render 'form' %>

<%= link_to 'Show', @college %> |
<%= link_to 'Back', colleges_path %>

app/views/colleges/import.html.erb
<div class="row">
	Import Products
	<%= form_tag import_colleges_path, multipart: true do %>
	  <%= file_field_tag :file %>
	  <%= submit_tag "Import" %>
	<% end %>
</div>

app/views/colleges/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Colleges</h1>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Name</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @colleges.each do |college| %>
      <tr>
        <td><%= college.code %></td>
        <td><%= college.name %></td>
        <td><%= college.location %></td>
        <td><%= link_to 'Show', college %></td>
        <td><%= link_to 'Edit', edit_college_path(college) %></td>
        <td><%= link_to 'Destroy', college, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New College', new_college_path %>

app/views/colleges/new.html.erb
<h1>New College</h1>

<%= render 'form' %>

<%= link_to 'Back', colleges_path %>

app/views/colleges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @college.code %>
</p>

<p>
  <strong>Name:</strong>
  <%= @college.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @college.location %>
</p>

<%= link_to 'Edit', edit_college_path(@college) %> |
<%= link_to 'Back', colleges_path %>