config/routes.rb
require 'subdomain'
Rails.application.routes.draw do
   
  resources :attachments
  
  get 'search/post'
  post 'search/fetch_post'
  get 'search/user'

  namespace :administrator do
    resources :roles
  end
  resources :activities
  resources :colleges do
    post :import, on: :collection
  end
  resources :answers
  resources :questions
  resources :content_images
  resources :post_category_images
  resources :profiles, param: :user_name do
    member do
      get :education
      get :basic_info
      get :social_info
      get :school_info
      get :college_info
      get :experience
      get :achievement
      get :project
      get :activity
      get :contributions
      resources :achievements
      resources :projects
      resources :experiences, param: :id
      resources :school_details
      resources :college_details
    end
  end
  
  root 'home#index'
  get 'home' => 'home#index', as: 'home'
  get 'browse_posts' => 'home#browse_posts', as: 'browse_posts'
  get 'help' => 'home#help', as: 'help'
  get 'join_us' => 'home#join_us', as: 'join_us'
  get 'to_do' => 'home#to_do', as: 'to_do'
  get 'volunteering' => 'home#volunteering', as: 'volunteering'
  get 'tags/:tag', to: 'home#tags', as: :tag
  
  resources :subscriptions
  
  namespace :administrator do
    resources :channel_types
    resources :channels
    resources :statuses
    resources :post_categories do
      get :fetch_categories_for_type, on: :collection
    end
    resources :posts do
      get '(page/:page)', :action => :index, :on => :collection, :as => ''
    end
  end
  resources :channels, except: :destory do
    collection do
      get :list_channels
      get :explore
      get :browse
      get :recommended
      get :my
    end
    member do 
      post :subscribe
      post :unfollow
      resources :channel_images
      get :followers
    end
    get :new_index
    resources :assignments
    resources :posts, only: :index, on: :member
  end
  resources :posts, param: :slug do
    get :my, on: :collection
    get :latest_post, on: :collection
    member do
      post :like
      post :dislike
      resources :embed_codes
      resources :post_images
      resources :post_contents
      resources :comments do 
        post :report_abuse
        get :reply
      end
    end
     get '(page/:page)', :action => :index, :on => :collection, :as => ''
  end

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks',
                                    registrations: 'users/registrations' }
  
  resources :users, param: :user_name do 
    collection do 
      get :pending
      get :completed
      get :incomplete
      get :sign_in_popup
    end
    member do
      get :following
      get :followers
      get :subscription
      get :my_classes
      get :manage_subscriptions
      get :fetch_receiver
      post :subscribe
      post :unfollow
      resources :messages do
        get '(page/:page)', :action => :index, :on => :collection, :as => ''
      end
    end
  end
  
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

end

app/models/post_content.rb
class PostContent < ActiveRecord::Base
  belongs_to :post
  belongs_to :channel
  has_many :content_images
  accepts_nested_attributes_for :content_images, allow_destroy: true, reject_if: :all_blank
  validates_presence_of :name
  validates_presence_of :description

end

app/controllers/post_contents_controller.rb
class PostContentsController < ApplicationController
  before_action :find_post
  before_action :set_post_content, only: [:show, :edit, :update, :destroy]

  # GET /post_contents
  # GET /post_contents.json
  def index
    @post_contents = @post.post_contents
  end

  # GET /post_contents/1
  # GET /post_contents/1.json
  def show
  end

  # GET /post_contents/new
  def new
    @post_content = PostContent.new
  end

  # GET /post_contents/1/edit
  def edit
  end

  # POST /post_contents
  # POST /post_contents.json
  def create
    @post_content = PostContent.new(post_content_params)

    respond_to do |format|
      if @post_content.save
        format.html { redirect_to @post_content, notice: 'Post content was successfully created.' }
        format.json { render :show, status: :created, location: @post_content }
      else
        format.html { render :new }
        format.json { render json: @post_content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /post_contents/1
  # PATCH/PUT /post_contents/1.json
  def update
    respond_to do |format|
      if @post_content.update(post_content_params)
        format.html { redirect_to @post_content, notice: 'Post content was successfully updated.' }
        format.json { render :show, status: :ok, location: @post_content }
      else
        format.html { render :edit }
        format.json { render json: @post_content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /post_contents/1
  # DELETE /post_contents/1.json
  def destroy
    @post_content.destroy
    respond_to do |format|
      format.html { redirect_to post_contents_url, notice: 'Post content was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post_content
      @post_content = PostContent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_content_params
      params.require(:post_content).permit(:content, :post_id, 
                                           :post_type_id,
                                           content_images_attributes: [:image, :_destroy, :id])
    end

    def find_post
      @post = if params[:id].to_i.nonzero?
                Post.find_by_id(params[:id])
              else
                Post.find_by_slug(params[:id])
              end
    end
end

app/helpers/post_contents_helper.rb
module PostContentsHelper
end

app/views/post_contents/_form.html.erb
<div class="row">
	<div class="large-8 columns">
		<%= semantic_form_for @post_content do |f| %>
		  <%= f.input :description %>
		  <%= f.input :post %>
		  <%= f.input :channel %>
		  <%= f.action :submit, :as => :input %>
		<% end %>
	</div>
</div>

app/views/post_contents/edit.html.erb
<h1>Editing Post Content</h1>

<%= render 'form' %>

<%= link_to 'Show', @post_content %> |
<%= link_to 'Back', post_contents_path %>

app/views/post_contents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Post Contents</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Post</th>
      <th>Post type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @post_contents.each do |post_content| %>
      <tr>
        <td><%= post_content.description %></td>
        <td><%= post_content.post.name %></td>
        <td><%= post_content.post.channel.name %></td>
        <td><%= link_to 'Show', post_content_path(post_content) %></td>
        <td><%= link_to 'Edit', edit_post_content_path(post_content) %></td>
        <td><%= link_to 'Destroy', post_content, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post content', new_post_content_path %>

app/views/post_contents/new.html.erb
<h1>New Post Content</h1>

<%= render 'form' %>

<%= link_to 'Back', post_contents_path %>

app/views/post_contents/show.html.erb
<div class='row'>
	<div class='large-2 columns'>
	  &nbsp;
	</div>
	<div class='large-8 columns end white-backgrnd' style="border: 1px solid #ddd">
		<div class='nav-links' style="border-bottom: 1px solid #ddd">	
			<ul class='inline-list'>
				<li>
					<%= link_to 'Manage Post', posts_path %>
				</li>
				<li>
					<%= link_to 'Post', post_path(@post) %>
				</li>
				<li class="active">
					<%= link_to 'Manage Contents', post_contents_path %>
				</li>
				<li>
					<%= link_to 'Manage Images', post_images_path %>
				</li>
				
			</ul>
		</div>
		<div class="container"  style="border: 1px solid #ddd">
			<p>
			  <strong>Content:</strong>
			  <%= raw @post_content.description %>
			</p>

			<p>
			  <strong>Post:</strong>
			  <%= @post_content.post.try(:name) %>
			</p>

			<p>
			  <strong>Channel:</strong>
			  <%= @post_content.channel.try(:name) %>
			</p>

			<%= link_to 'Edit', edit_post_content_path(@post_content) %> |
			<%= link_to 'Back', post_contents_path %>
		</div>
		<br>
	</div>
</div>
<br>