config/routes.rb
require 'subdomain'
Rails.application.routes.draw do
   
  resources :attachments
  
  get 'search/post'
  post 'search/fetch_post'
  get 'search/user'

  namespace :administrator do
    resources :roles
  end
  resources :activities
  resources :colleges do
    post :import, on: :collection
  end
  resources :answers
  resources :questions
  resources :content_images
  resources :post_category_images
  resources :profiles, param: :user_name do
    member do
      get :education
      get :basic_info
      get :social_info
      get :school_info
      get :college_info
      get :experience
      get :achievement
      get :project
      get :activity
      get :contributions
      resources :achievements
      resources :projects
      resources :experiences, param: :id
      resources :school_details
      resources :college_details
    end
  end
  
  root 'home#index'
  get 'home' => 'home#index', as: 'home'
  get 'browse_posts' => 'home#browse_posts', as: 'browse_posts'
  get 'help' => 'home#help', as: 'help'
  get 'join_us' => 'home#join_us', as: 'join_us'
  get 'to_do' => 'home#to_do', as: 'to_do'
  get 'volunteering' => 'home#volunteering', as: 'volunteering'
  get 'tags/:tag', to: 'home#tags', as: :tag
  
  resources :subscriptions
  
  namespace :administrator do
    resources :channel_types
    resources :channels
    resources :statuses
    resources :post_categories do
      get :fetch_categories_for_type, on: :collection
    end
    resources :posts do
      get '(page/:page)', :action => :index, :on => :collection, :as => ''
    end
  end
  resources :channels, except: :destory do
    collection do
      get :list_channels
      get :explore
      get :browse
      get :recommended
      get :my
    end
    member do 
      post :subscribe
      post :unfollow
      resources :channel_images
      get :followers
    end
    get :new_index
    resources :assignments
    resources :posts, only: :index, on: :member
  end
  resources :posts, param: :slug do
    get :my, on: :collection
    get :latest_post, on: :collection
    member do
      post :like
      post :dislike
      resources :embed_codes
      resources :post_images
      resources :post_contents
      resources :comments do 
        post :report_abuse
        get :reply
      end
    end
     get '(page/:page)', :action => :index, :on => :collection, :as => ''
  end

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks',
                                    registrations: 'users/registrations' }
  
  resources :users, param: :user_name do 
    collection do 
      get :pending
      get :completed
      get :incomplete
      get :sign_in_popup
    end
    member do
      get :following
      get :followers
      get :subscription
      get :my_classes
      get :manage_subscriptions
      get :fetch_receiver
      post :subscribe
      post :unfollow
      resources :messages do
        get '(page/:page)', :action => :index, :on => :collection, :as => ''
      end
    end
  end
  
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

end

app/models/post_image.rb
class PostImage < ActiveRecord::Base
  belongs_to :post_content
  belongs_to :post
  belongs_to :channel
  mount_uploader :image, ImageUploader
end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController
  before_action :find_post
  before_action :set_post_image, only: [:show, :edit, :update, :destroy]
  
  # GET /post_images
  # GET /post_images.json
  def index
    @post_images = @post.post_images
  end

  # GET /post_images/1
  # GET /post_images/1.json
  def show
    respond_to do |format|
      format.html
      format.pdf { render pdf: generate_pdf(@post_image) }
    end
  end

  # GET /post_images/new
  def new
    @post_image = @post.post_images.new
  end

  # GET /post_images/1/edit
  def edit
  end

  # POST /post_images
  # POST /post_images.json
  def create
    @post_image = @post.post_images.new(post_image_params)

    respond_to do |format|
      if @post_image.save
        format.html { redirect_to @post_image, notice: 'Post image was successfully created.' }
        format.json { render :show, status: :created, location: @post_image }
      else
        format.html { render :new }
        format.json { render json: @post_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /post_images/1
  # PATCH/PUT /post_images/1.json
  def update
    respond_to do |format|
      if @post_image.update(post_image_params)
        format.html { redirect_to @post_image, notice: 'Post image was successfully updated.' }
        format.json { render :show, status: :ok, location: @post_image }
      else
        format.html { render :edit }
        format.json { render json: @post_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /post_images/1
  # DELETE /post_images/1.json
  def destroy
    @post_image.destroy
    respond_to do |format|
      format.html { redirect_to post_images_url, notice: 'Post image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post_image
      @post_image = PostImage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_image_params
      params.require(:post_image).permit(:name, :description, :post_id, :image)
    end

    def find_post
      @post = if params[:id].to_i < 0
                Post.find_by_id(params[:id])
              else
                Post.find_by_slug(params[:id])
              end
    end
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/views/post_images/_form.html.erb
<%= semantic_form_for @post_image, inner_html: { multipart: true } do |f| %>
  <%= f.inputs do %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :image, as: :file %>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :input %>
  <% end %>
<% end %>

app/views/post_images/edit.html.erb
<h1>Editing Post Image</h1>

<%= render 'form' %>

<%= link_to 'Show', @post_image %> |
<%= link_to 'Back', post_images_path %>

app/views/post_images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Post Images</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody
    <% @post_images.each do |post_image| %>
      <tr>
        <td><%= post_image.name %></td>
        <td><%= post_image.description %></td>
        <td><%= post_image.try(:post).try(:name) %></td>
        <td><%= image_tag(post_image.try(:image).try(:small)) %></td>
        <td><%= link_to 'Show', post_image_path(post_image.post, post_image) %></td>
        <td><%= link_to 'Edit', edit_post_image_path(post_image.post, post_image) %></td>
        <td><%= link_to 'Destroy', post_image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post image', new_post_image_path %>

app/views/post_images/new.html.erb
<h1>New Post Image</h1>

<%= render 'form' %>

<%= link_to 'Back', post_images_path %>

app/views/post_images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @post_image.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @post_image.description %>
</p>

<p>
  <strong>Post:</strong>
  <%= @post_image.post.name %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag(@post_image.image.small) %>
</p>

<%= link_to 'Edit', edit_post_image_path(@post_image) %> |
<%= link_to 'Back', post_images_path %>